name: CMake Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    name: Build on x64 Release
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Configure CMake
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
      working-directory: ${{ github.workspace }}

    - name: Build
      run: cmake --build build --config Release --target all
      working-directory: ${{ github.workspace }}
